on:
  release:
    types: [published]

jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: GitHub Releases to Discord
        uses: SethCohen/github-releases-to-discord@v1
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          content: "A new version of Complicated Bees has been pushed to CurseForge and Modrinth! It should be approved within 24 hours. It is also available immediately on the [GitHub.](https://github.com/ACCBDD/reclamation-dev)"
          reduce_headings: true